In [2]:
from statistics import stdev

# For data manipulation and visualization
import pandas as pd
import altair as alt

# Aula 8 - Medidas centrais de resumo

## Aplique seu conhecimento 2.2 (p.40) - Despesas com cuidados da saúde

A base abaixo mostra as despesas anuais, em 2015, com cuidados da saúde por pessoa, nos 35 países com os maiores valores do PIB em 2015.

In [3]:
cuidasaude = pd.read_excel(f'ex02-02health.xls')

In [4]:
cuidasaude.sort_values('Dollars',ascending=False)

               Country  Dollars
33        UnitedStates     9536
28         Switzerland     7583
21              Norway     6222
10             Germany     5357
19         Netherlands     5313
27              Sweden     5299
2              Austria     5138
8              Denmark     5083
3              Belgium     4782
5               Canada     4600
9               France     4542
1            Australia     4492
15               Japan     4405
32       UnitedKingdom     4145
14               Italy     3351
26               Spain     3183
24         SaudiArabia     3121
16               Korea     2556
31  UnitedArabEmirates     2426
22              Poland     1704
23              Russia     1414
4               Brazil     1392
0            Argentina     1390
13                Iran     1262
25         SouthAfrica     1086
17            Malaysia     1064
18              Mexico     1009
30              Turkey      996
7             Colombia      853
6                China      762
29            Thailand      610
12           Indonesia      369
11               India      238
20             Nigeria      215
34           Venezuela      106

Os Estados Unidos com 9.536 dólares internacionais por pessoa, é um alto valor atípico superior. Ache a média das despesas com cuidados da saúde nesses países, com e sem os Estados Unidos. De quanto o valor atípico aumenta a média?

In [5]:
print(cuidasaude['Dollars'].mean())

3017.2571428571428

In [6]:
print(cuidasaude[cuidasaude.Country!="UnitedStates"]['Dollars'].mean())

2825.529411764706

Ao retirar os Estados Unidos, podemos observar que a média teve uma redução de mais de 200 dólares. Será que a mediana sofre também uma grande alteração com a retirada desse valor?

In [7]:
print(cuidasaude['Dollars'].median())

2556.0

In [8]:
print(cuidasaude[cuidasaude.Country!="UnitedStates"]['Dollars'].median())

2491.0

Podemos observar que a mediana não sofreu tanta alteração, pois é resistente a valores atípicos.

Vamos visualizar o gráfico para verificar quão distante esse possível valor atípico está dos outros países.

In [9]:
alt.Chart(cuidasaude).mark_bar().encode(
    alt.X("Dollars:Q", bin=True),
    y='count()',
)

alt.Chart(...)

O Altair está considerando intervalos de tamanho 1000. Como ficaria o gráfico se quiséssemos diminuir o tamanho dos intervalos das classes?

In [10]:
alt.Chart(cuidasaude).mark_bar().encode(
    alt.X("Dollars:Q", bin=alt.Bin(step=200)),
    y='count()',
)

alt.Chart(...)

Ficaria muito mais difícil de perceber o padrão geral dessa distribuição. Apesar de não ter uma escolha certa para os tamanhos dos intervalos, essa escolha é determinante para gerar uma boa visualização da distribuição de uma variável quantitativa.

## Exemplo 2.1 (p.39) - Tempo de viagem para o trabalho Carolina do Norte

A Pesquisa da Comunidade Americana pergunta, dentre muitas outras coisas, o tempo de viagem para o trabalho. Abaixo temos o tempo de viagem para 15 trabalhadores da Carolina do Norte, escolhidos aleatoriamente pelo Census Bureau.

In [11]:
tempocn = pd.read_excel('eg02-01nctravel.xls')

In [12]:
tempocn

    Minutes
0        20
1        35
2         8
3        70
4         5
5        15
6        25
7        30
8        40
9        35
10       10
11       12
12       40
13       15
14       20

O tempo médio de viagem dos 15 trabalhadores é:

In [13]:
print(tempocn.Minutes.mean())

25.333333333333332

In [14]:
tempocn[tempocn.Minutes > tempocn.Minutes.mean()]

    Minutes
1        35
3        70
7        30
8        40
9        35
12       40

Note que apenas 6 dos 15 tempos de viagem são maiores do que a média.

Abaixo, podemos observar que se desprezarmos o maior tempo de viagem, 70 minutos, a média para os restantes 14 será 22.1 minutos. Essa única observação eleva a média em 3.2 minutos.

In [15]:
print(tempocn.Minutes.max())

70

In [16]:
print(tempocn[tempocn.Minutes < 70].Minutes.mean())

22.142857142857142

Por outro lado, a mediana permanece a mesma com ou sem o maior tempo.

In [17]:
print(tempocn.Minutes.median())

20.0

In [18]:
print(tempocn[tempocn.Minutes < 70].Minutes.median())

20.0

Vamos visualizar a distribuição de frequência desse dado.

In [19]:
alt.Chart(tempocn).mark_bar().encode(
    alt.X("Minutes:Q", bin=True),
    y='count()',
)

alt.Chart(...)

Uma forma de calcular a moda com value_counts.

In [20]:
tempocn.Minutes.value_counts()

Minutes
20    2
35    2
15    2
40    2
8     1
70    1
5     1
25    1
30    1
10    1
12    1
Name: count, dtype: int64

Podemos ver que essa distribuição é plurimodal, pois as maiores frequências acontecem em quatro tempos de viagem diferentes.

Por outro lado, se olharmos para as classes do nosso gráfico, a classe que mais concentra observações é para indivíduos que leva de 10 a menos que 20 minutos para chegar ao trabalho (fechado em 10 e aberto em 20).

## Aplique seu conhecimento 2.3 (p.41) - Tempo de viagem para o trabalho New York

Agora, considere o tempo de viagem para o trabalho de 20 trabalhadores do estado de Nova York, escolhidos aleatoriamente.

In [21]:
tempony = pd.read_excel(f'eg02-03nytravel.xls')

In [22]:
tempony

    Minutes
0        10
1        15
2        55
3        20
4        65
5        50
6        12
7        20
8        10
9        10
10       35
11       50
12       30
13       45
14       15
15       10
16       75
17       40
18       35
19       60

Compare a média e a mediana. Que fato geral sua comparação ilustra?

In [23]:
print(tempony.Minutes.median())

32.5

In [24]:
print(tempony.Minutes.mean())

33.1

A média é pouco maior que a mediana, mas não é tanto a ponto de afirmarmos apenas por esses valor que essa é uma distribuição assimétrica à direita. Pode ser que a distribuição se aproxime de uma simetria. Vamos observar o gráfico.

In [25]:
alt.Chart(tempony).mark_bar().encode(
    alt.X("Minutes:Q", bin=True),
    y='count()',
)

alt.Chart(...)

## Aplique seu conhecimento 2.5 (p.41) - Emissões de dióxido de carbono

A base abaixo fornece as emissões de carbono (CO2) por pessoa, em 2010, para países com população de, no mínimo, 30 milhões. Ache a média e a mediana para esses dados. Faça um histograma dos dados. Quais as características da distribuição explicam por que a média é maior do que a mediana?

In [26]:
emissaoco2 = pd.read_excel(f'ex02-05co2emiss.xls')

In [27]:
emissaoco2

          Country  CO2 emissions
0           Aruba       8.410064
1     Afghanistan       0.293946
2          Angola       1.290307
3         Albania       1.978763
4         Andorra       5.832906
..            ...            ...
198         Samoa       1.030158
199   Yemen, Rep.       0.878996
200  South Africa       8.979062
201        Zambia       0.292412
202      Zimbabwe       0.884721

[203 rows x 2 columns]

In [28]:
print(emissaoco2['CO2 emissions'].median())

2.753266363412166

In [29]:
print(emissaoco2['CO2 emissions'].mean())

4.967597247846716

A média é consideravelmente maior que a mediana, o que aponta para uma distribuição assimétrica à direita. Vamos verificar o gráfico.

In [30]:
alt.Chart(emissaoco2).mark_bar().encode(
    alt.X("CO2 emissions:Q", bin=alt.Bin(step=2)),
    y='count()'
)

alt.Chart(...)

Qual país mais emite CO2?

In [31]:
emissaoco2.sort_values('CO2 emissions', ascending=False)

                      Country  CO2 emissions
151                     Qatar      43.857308
44                    Curacao      37.726289
183       Trinidad and Tobago      33.966414
100                    Kuwait      25.849229
18                    Bahrain      23.455406
..                        ...            ...
30   Central African Republic       0.067357
37           Congo, Dem. Rep.       0.063331
176                      Chad       0.053407
163                   Somalia       0.045347
12                    Burundi       0.044700

[203 rows x 2 columns]

Qatar é o país que mais emite, é o país que está na última classe do gráfico, com emissão entre 42 e 44 por pessoa.

# Aula 9 - Quartis, Valores Atípicos e Boxplot

## Exemplo 2.4 (p.42) - Tempo de viagem para o trabalho Carolina do Norte

Voltando aos dados de Carolina do Norte, vamos analisar o intervalo interquartil como uma medida de dispersão.

Podemos calcular todas as medidas descritivas de uma só vez, com a função describe.

In [32]:
tempocn.describe()

         Minutes
count  15.000000
mean   25.333333
std    16.969160
min     5.000000
25%    13.500000
50%    20.000000
75%    35.000000
max    70.000000

Dessa forma, temos que o Q1 é 13.5 e Q3 é 35. Podemos, portando, calcular a amplitude interquartil como a diferença desses dois quartis.

In [33]:
aiq_cn = 35-13.5
print(f"AIQ = {aiq_cn}")

AIQ = 21.5

Para avaliarmos se 70 é de fato um potencial valor atípico, como supusemos acima ao avaliamos o tanto que esse valor influencia na média, vamos usar a regra 1.5xAIQ.

Para um valor ser considerado potencialmente atípico, ele precisa estar fora do intervalor que [Q1 - 1.5xAIQ; Q3 + 1.5xAIQ], que nesse caso é o intervalo:

In [34]:
print(f"[{3.5-1.5*aiq_cn}; {35+1.5*(aiq_cn)}]")

[-28.75; 67.25]

Confirmamos, portanto, que por essa regra, o tempo de 70 minutos pode ser considerado um valor atípico.

Vamos visualizar o boxplot dessa distribuição.

In [35]:
alt.Chart(tempocn).mark_boxplot(extent='min-max').encode(
    y='Minutes:Q'
).properties(width=200)

alt.Chart(...)

Esse boxplot do ponto mínimo ao ponto máximo da distribuição, o que foi determinado pelo parâmetro `extent="min-max`. Para considerarmos a visualização que destaque o valor atípico, pela regra 1.5xAIQ, podemos alterar esse parâmetro para `extent=1.5`.

In [36]:
alt.Chart(tempocn).mark_boxplot(extent=1.5).encode(
    y='Minutes:Q'
).properties(width=200)

alt.Chart(...)

## Exemplo 2.5 (p.42) - Tempo de viagem para o trabalho New York

Agora, vamos considerar novamente o tempo de viagem para o trabalho dos 20 trabalhadores do estado de Nova York e visualizar seu boxplot.

In [37]:
alt.Chart(tempony).mark_boxplot(extent=1.5).encode(
    y='Minutes:Q'
).properties(width=200)

alt.Chart(...)

Esse conjunto de dados não tem nenhum potencial valor atípico.

## Os dois juntos considerando valor atípico

Para fazer uma análise comparativa das distribuições, vamos visualizar os dois boxplots juntos em um mesmo gráfico.

Para isso, é preciso criar uma base que agregue os dois dados.

In [38]:
tempocn['Origin'] = "Carolina do Norte"
tempony['Origin'] = "Nova York"

tempo_viagem = pd.concat([tempocn,tempony])

tempo_viagem

    Minutes             Origin
0        20  Carolina do Norte
1        35  Carolina do Norte
2         8  Carolina do Norte
3        70  Carolina do Norte
4         5  Carolina do Norte
5        15  Carolina do Norte
6        25  Carolina do Norte
7        30  Carolina do Norte
8        40  Carolina do Norte
9        35  Carolina do Norte
10       10  Carolina do Norte
11       12  Carolina do Norte
12       40  Carolina do Norte
13       15  Carolina do Norte
14       20  Carolina do Norte
0        10          Nova York
1        15          Nova York
2        55          Nova York
3        20          Nova York
4        65          Nova York
5        50          Nova York
6        12          Nova York
7        20          Nova York
8        10          Nova York
9        10          Nova York
10       35          Nova York
11       50          Nova York
12       30          Nova York
13       45          Nova York
14       15          Nova York
15       10          Nova York
16       75          Nova York
17       40          Nova York
18       35          Nova York
19       60          Nova York

In [39]:
alt.Chart(tempo_viagem).mark_boxplot(extent=1.5, size=40).encode(
    alt.X("Minutes:Q"),
    alt.Y("Origin:N")
    #alt.Color("Origin:N")
).properties(height=200)

alt.Chart(...)

Essa análise comparativa mostra a assimetria à direita mais acentuada para Carolina do Norte, inclusive com a presença de um valor atípico.

Mas deixa claro também, pelo tamanho do AIQ, que a dispersão da distribuição de Nova York é maior. O tamanho do boxplot de NY e a falta de valores atípicos também aponta para uma distribuição que se estende por um intervalo maior.

Além disso, no geral, o tempo de viagem dos moradores de NY até o trabalho é maior do que dos moradores de Carolina do Norte, já que há um deslocamento do gráfico todo de Nova York para a direita.

# Aula 10 - Desvio Padrão

## Exemplo das notas das turmas

In [40]:
turma_a = [4,5,5,6,6,7,7,8]
turma_b = [1,2,4,6,6,9,10,10]
turma_c = [0,6,7,7,7,7.5,7.5]

In [41]:
from statistics import stdev, mean, median

print(f"Turma A: média = {mean(turma_a)} ; desvio padrão = {stdev(turma_a)}")
print(f"Turma B: média = {mean(turma_b)} ; desvio padrão = {stdev(turma_b)}")
print(f"Turma C: média = {mean(turma_c)} ; desvio padrão = {stdev(turma_c)}")

Turma A: média = 6 ; desvio padrão = 1.3093073414159544
Turma B: média = 6 ; desvio padrão = 3.5050983275386565
Turma C: média = 6.0 ; desvio padrão = 2.692582403567252

In [42]:
# outra forma de calcular, com describe
print(pd.DataFrame(turma_a).describe().loc[['mean','std']])
print(pd.DataFrame(turma_b).describe().loc[['mean','std']])
print(pd.DataFrame(turma_c).describe().loc[['mean','std']])

             0
mean  6.000000
std   1.309307
             0
mean  6.000000
std   3.505098
             0
mean  6.000000
std   2.692582

Verificamos, através das médias, que os alunos das três turmas tenderam a ter as notas em tomo de seis, mas, pelos desvios padrões, concluímos que os alunos da Turma A obtiveram notas relativamente próximas umas das outras, quando comparados aos alunos das outras turmas. Por outro lado, as notas dos alunos da Turma B foram as que se apresentaram mais heterogêneas.

# Exercícios

## De volta às bases anteriores

Volte às bases de dados anteriores, inclusive as que vimos nas outras aulas, e observe os valores dos resumos numéricos (média e desvio padrão / resumo dos 5 números) e como eles representam a forma das distribuições e dão características sobre elas. Para isso, pode usar a função describe do pandas. E para uma interpretação mais completa, avalie conjuntamente os resumos numéricos e o gráfico das suas distribuições.

## **Caso - Parceiros sexuais**

Realize análises com as variáveis quantitativas da base de dados do caso lido. Lembre-se das análises que são feitas no caso, como representação gráfica e avaliação dos resumos numéricos.

In [43]:
parceiros = pd.read_csv('02-4-sexual-partners-counts-x.csv')

In [44]:
parceiros

     NumPartners  MenCount  MenPercent  WomenCount  WomenPercent
0              0         6        0.75           5          0.42
1              1       100       12.56         212         17.77
2              2        44        5.53          93          7.80
3              3        39        4.90         130         10.90
4              4        58        7.29          88          7.38
..           ...       ...         ...         ...           ...
132          403         1        0.13           0          0.00
133          450         0        0.00           0          0.00
134          500         1        0.13           0          0.00
135          501         1        0.13           0          0.00
136          550         0        0.00           1          0.08

[137 rows x 5 columns]

Histograma de número de parceiros dos homens

In [45]:
alt.Chart(parceiros).mark_bar().encode(
    x=alt.X('NumPartners:Q', bin=alt.Bin(step=1)),
    y=alt.Y('MenCount:Q', title='Percentage'),
    tooltip=['NumPartners', 'MenCount']
).properties(
    width=5000,
    height=800
)

alt.Chart(...)

Histograma do número de parceiros de mulheres

In [46]:
alt.Chart(parceiros).mark_bar().encode(
    x=alt.X('NumPartners:Q', bin=alt.Bin(step=1)),
    y=alt.Y('WomenCount:Q', title='Percentage'),
    tooltip=['NumPartners', 'WomenCount']
).properties(
    width=5000,
    height=800
)

alt.Chart(...)

Para criarmos o gráfico exatamente igual ao do caso, precisamos transformar a base em formado long.

In [47]:
parceiros_melted = parceiros.melt(id_vars=['NumPartners'], value_vars=['MenPercent', 'WomenPercent'], var_name='Gender', value_name='Percentage')

In [48]:
parceiros_melted

     NumPartners        Gender  Percentage
0              0    MenPercent        0.75
1              1    MenPercent       12.56
2              2    MenPercent        5.53
3              3    MenPercent        4.90
4              4    MenPercent        7.29
..           ...           ...         ...
269          403  WomenPercent        0.00
270          450  WomenPercent        0.00
271          500  WomenPercent        0.00
272          501  WomenPercent        0.00
273          550  WomenPercent        0.08

[274 rows x 3 columns]

In [49]:
chart = alt.Chart(parceiros_melted).mark_bar().encode(
    x=alt.X('Gender:N', axis=None),
    y=alt.Y('Percentage:Q', title='Percentage'),
    color='Gender:N',
    column=alt.Column('NumPartners:Q', spacing=1),
    tooltip=['NumPartners', 'Percentage', 'Gender']
).properties(
    width=10,  # ajusta a largura das barras
    height=400
)

chart

alt.Chart(...)

Calculando as medidas de centro e dispersão para homens e para mulheres

In [50]:
parceiros[['NumPartners','MenCount']].reindex(parceiros[['NumPartners','MenCount']].index.repeat(parceiros[['NumPartners','MenCount']].MenCount)).reset_index(drop=True).NumPartners.describe()

count    796.000000
mean      16.978643
std       37.807367
min        0.000000
25%        4.000000
50%        8.000000
75%       20.000000
max      501.000000
Name: NumPartners, dtype: float64

In [51]:
parceiros[['NumPartners','WomenCount']].reindex(parceiros[['NumPartners','WomenCount']].index.repeat(parceiros[['NumPartners','WomenCount']].WomenCount)).reset_index(drop=True).NumPartners.describe()

count    1193.000000
mean        8.230511
std        17.955052
min         0.000000
25%         2.000000
50%         5.000000
75%        10.000000
max       550.000000
Name: NumPartners, dtype: float64